"""
Regenerates audio.wav (silent CIA banner audio - bannertool needs some
audio file even though the app makes no sound).

icon.png and banner.png are NOT generated by this script - they're the
real Home Assistant logo, sourced from home-assistant/android's app icon
(mipmap-xxxhdpi/ic_launcher.png, 192x192) and resized/composited with
.NET System.Drawing. To regenerate them from a newer logo:

  1. Download the source PNG, e.g.:
     https://raw.githubusercontent.com/home-assistant/android/master/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  2. Resize to 48x48 -> icon.png (bannertool's required icon size).
  3. Composite centered (roughly 100x100) on a solid background -> 256x128
     banner.png (bannertool's required banner size).

Re-run with: python gen_placeholder_assets.py
"""
import struct
import wave


def write_silent_wav(path, seconds=1, sample_rate=32728):
    nframes = seconds * sample_rate
    silence = struct.pack("<h", 0) * 2 * nframes
    with wave.open(path, "w") as w:
        w.setnchannels(2)
        w.setsampwidth(2)
        w.setframerate(sample_rate)
        w.writeframes(silence)


if __name__ == "__main__":
    write_silent_wav("audio.wav")
    print("Wrote audio.wav (icon.png/banner.png are real HA branding - see this file's docstring)")
